# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wado9\PycharmProjects\EXS_calc\input_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_InputPassword(object):
    def setupUi(self, Dialog_InputPassword):
        Dialog_InputPassword.setObjectName("Dialog_InputPassword")
        Dialog_InputPassword.resize(508, 114)
        self.pushButton_Cancel = QtWidgets.QPushButton(Dialog_InputPassword)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(70, 80, 80, 25))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.pushButton_Ok = QtWidgets.QPushButton(Dialog_InputPassword)
        self.pushButton_Ok.setGeometry(QtCore.QRect(340, 80, 80, 25))
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        self.label = QtWidgets.QLabel(Dialog_InputPassword)
        self.label.setGeometry(QtCore.QRect(60, 20, 451, 17))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog_InputPassword)
        self.lineEdit.setGeometry(QtCore.QRect(70, 50, 351, 23))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog_InputPassword)
        QtCore.QMetaObject.connectSlotsByName(Dialog_InputPassword)

    def retranslateUi(self, Dialog_InputPassword):
        _translate = QtCore.QCoreApplication.translate
        Dialog_InputPassword.setWindowTitle(_translate("Dialog_InputPassword", "Dialog"))
        self.pushButton_Cancel.setText(_translate("Dialog_InputPassword", "Отмена"))
        self.pushButton_Ok.setText(_translate("Dialog_InputPassword", "Ок"))
        self.label.setText(_translate("Dialog_InputPassword", "Введите пароль, чтобы получить права Главного технолога"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_InputPassword = QtWidgets.QDialog()
    ui = Ui_Dialog_InputPassword()
    ui.setupUi(Dialog_InputPassword)
    Dialog_InputPassword.show()
    sys.exit(app.exec_())
